name: rris-codd
channels:
  - pytorch
  - nvidia
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.90
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.1.3
  - libcurand=10.3.9.90
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pip=25.0
  - pysocks=1.7.1
  - python=3.10.16
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2023.11.17
      - cffi==1.17.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - crcmod==1.7
      - cryptography==44.0.1
      - cycler==0.12.1
      - cython==3.0.8
      - filelock==3.14.0
      - fonttools==4.47.2
      - fsspec==2025.2.0
      - h2==4.1.0
      - hpack==4.0.0
      - huggingface-hub==0.28.1
      - hyperframe==6.0.1
      - idna==3.6
      - imageio==2.37.0
      - jinja2==3.1.3
      - jmespath==0.10.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.6
      - model-index==0.1.11
      - munkres==1.1.4
      - networkx==3.2.1
      - numpy==1.25.2
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.0
      - pandas==2.2.3
      - pillow==10.2.0
      - platformdirs==4.3.6
      - pycocotools==2.0.7
      - pycparser==2.21
      - pycryptodome==3.21.0
      - pygments==2.19.1
      - pyparsing==3.1.1
      - python-box==7.3.2
      - python-dateutil==2.8.2
      - pytz==2023.4
      - pywavelets==1.8.0
      - pyyaml==6.0.1
      - regex==2024.11.6
      - registry==0.4.2
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.5.2
      - scikit-image==0.19.3
      - scikit-learn==1.6.1
      - scipy==1.9.2
      - setuptools==60.2.0
      - six==1.16.0
      - svgwrite==1.4.3
      - sympy==1.12
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - timm==0.9.10
      - tokenizers==0.15.0
      - tomli==2.2.1
      - tqdm==4.65.0
      - transformers==4.35.2
      - tree==0.2.4
      - typing-extensions==4.9.0
      - tzdata==2025.1
      - urllib3==1.26.20
      - yacs==0.1.8
      - yapf==0.43.0
      - zstandard==0.23.0
